# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: Sayo / Jelly
email: jelly@sayo.dev
description: >-
  I like creating random projects and never finishing them, and procrastination too! (don't wanna forget that one!)
  <br>Hope you enjoy! <3
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sayo.dev" # the base hostname & protocol for your site, e.g. http://example.com

twitter_link: https://www.twitter.com/SayoJellyDev
youtube_link: https://www.youtube.com/@SayoDev
discord_link: https://discord.gg/TQJjnEsh3E
github_link:  https://github.com/SayoJellyDev

# Build settings
plugins:
  - jekyll-feed


collections_dir: site_collections

# Jekyll wil check this folder for the following collections below!
# Much neater :D!

collections:
  projects:
    output: true
  commissions:
    output: true

sass:
  style: compressed

exclude: 
  - "assets/css/css.scss"
  - "assets/js/app.js"

keep_files: 
  - "assets/css/css.css"
  - "assets/js/app.js"